project:
  type: website

website:
  title: "til"
  description: "chekos' today i learned"
  site-url: "https://til.chekos.dev"
  repo-url: https://github.com/chekos/til
  reader-mode: true
  open-graph: true 
  twitter-card: 
    creator: "@ChekosWH"
    card-style: summary_large_image 
  navbar:
    logo: /images/cimarron-logo-no-background.png
    background: secondary
    right:
      - about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/chekos/til
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/chekoswh
      - icon: mastodon
        aria-label: mastodon
        href: https://masto.tacosdedatos.com/@chekos
      - icon: person-circle
        aria-label: website
        href: https://soyserg.io
      - icon: instagram
        aria-label: instagram
        href: https://instagram.com/chekos.visuals
      - icon: rss
        aria-label: rss
        href: index.xml
        
format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: /css/styles.css
    code-fold: true
    code-line-numbers: true
    code-copy: true
    toc: true
    toc-location: left
    anchor-sections: true
    title-block-categories: false
    title-block-banner: false

self-contained: true 
jupyter: python3
execute: 
  freeze: true
  error: false
  warning: false
