name: Publish to gh-pages

on:
  workflow_dispatch:
  push:
    paths:
      - "tils/**"
      - "about.qmd"
      - "index.qmd"
      - "_quarto.yml"

jobs:
  organize-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install -r dev-requirements.txt
      - name: Move posts
        run: |-
          python3 scripts/move_posts.py
      - name: Commit and push if it changed 
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Posts moved: ${timestamp}" || exit 0
          echo '### Changed files' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          git show --name-only --format=tformat: >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          git pull --rebase
          git push
  build-deploy:
    if: ${{ always() }}
    needs: organize-posts
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - name: Install Python dependencies
        run: |-
          pip install -r requirements.txt
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
